DROP TABLE IF EXISTS ICFT_USER;
/**
	用户表
*/
CREATE TABLE ICFT_USER(
	ID INT(8) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	USERNAME VARCHAR(10) COMMENT '用户名',
	PSW VARCHAR(30) NOT NULL COMMENT '密码',
	USERINFOID INT(8) NOT NULL COMMENT '用户信息表id',
	PRIMARY KEY(ID)
)COMMENT '用户表';

DROP TABLE IF EXISTS ICFT_USER_INFO;
/**
	用户信息表
*/
CREATE TABLE ICFT_USER_INFO(
	ID INT(8) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	NINAME VARCHAR(20) NOT NULL COMMENT '昵称',
	CAPITAL DOUBLE(10,2) NOT NULL COMMENT '资产',
	SEX INT(2) NOT NULL COMMENT '性别',
	AGE INT(3) NOT NULL COMMENT '年龄',
	BIRTHDAY VARCHAR(20) NOT NULL COMMENT '生日',
	COUNTRY VARCHAR(10) COMMENT '国家',
	CITY VARCHAR(10) COMMENT '城市',
	CREATETIME VARCHAR(20) COMMENT '创建时间',
	UPDATETIME VARCHAR(20) COMMENT '更新时间',
	PRIMARY KEY(ID)
)COMMENT '用户信息表';

DROP TABLE IF EXISTS ICFT_CAPITAL_DETAIL;
/**
	资金明细表
*/
CREATE TABLE ICFT_CAPITAL_DETAIL(
	ID INT(8) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	USEWAYID INT(8) NOT NULL COMMENT '用途ID',
	RMB DOUBLE(10,2) NOT NULL COMMENT '花费',
	ISADD INT(2) NOT NULL COMMENT '增减',
	CREATETIME VARCHAR(20) COMMENT '创建时间',
	PRIMARY KEY(ID)
)COMMENT '资金明细表';


DROP TABLE IF EXISTS ICFT_USEWAY;
/**
	用途表
*/
CREATE TABLE ICFT_USEWAY(
	ID INT(8) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	USEWAYNAME VARCHAR(20) NOT NULl COMMENT '用途名',
	PRIMARY KEY(ID)
)COMMENT '用途表';



DROP TABLE IF EXISTS ICFT_HISTORY;
/**
	历史表
*/
CREATE TABLE ICFT_HISTORY(
	ID INT(8) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	OPERATORTYPE INT(4) NOT NULl COMMENT '操作类型',
	CREATETIME VARCHAR(20) COMMENT '创建时间',
	PRIMARY KEY(ID)
)COMMENT '历史表';